// client-sv/src/lib/character/components/CharacterImage.svelte
<script lang="ts">
  import { drawCharacterImage } from "$lib/character/utils/draw-character-image";
  import type { CharacterClass } from "@fwo/shared";

  const {
    characterClass,
    small,
  }: { characterClass: CharacterClass; small?: boolean } = $props();
  let canvas: HTMLCanvasElement;

  const width = $derived(small ? 20 : 100);
  const height = $derived(small ? 20 : 100);

  $effect(() => {
    drawCharacterImage(canvas, characterClass);
  });
</script>

<canvas bind:this={canvas} style="margin: auto" {width} {height}></canvas>

// client/modules/character/components/CharacterImage.tsx
import { type FC, useEffect, useRef } from 'react';
import { drawCharacter } from '@/modules/character/hooks/useDrawCharacter';
import type { CharacterClass } from '@fwo/shared';

export const CharacterImage: FC<{ characterClass: CharacterClass; small?: boolean }> = ({
  characterClass,
  small,
}) => {
  const canvas = useRef<HTMLCanvasElement>(null);
  const width = small ? 20 : 100;
  const height = small ? 20 : 100;

  useEffect(() => {
    if (canvas.current) {
      drawCharacter(canvas.current, characterClass);
    }
  }, [characterClass]);

  return <canvas ref={canvas} style={{ margin: 'auto' }} width={width} height={height} />;
};
