// client/components/Player/Player.tsx
import type { CharacterClass } from '@fwo/shared';
import classNames from 'classnames';
import type { FC, ReactNode } from 'react';
import { CharacterImage } from '@/modules/character/components/CharacterImage';

export const Player: FC<{
  className?: string;
  class: CharacterClass;
  name: string;
  lvl?: number;
  isBot?: boolean;
  append?: ReactNode;
}> = ({ className, class: characterClass, name, lvl, isBot, append }) => {
  return (
    <div className={classNames('inline-flex justify-start gap-2', className)}>
      {lvl ? lvl : null}
      {isBot ? null : <CharacterImage characterClass={characterClass} small />}
      <div className="flex-1">{name}</div>
      {append ? append : null}
    </div>
  );
};

// client/src/lib/lobby/components/Player.svelte
<script lang="ts">
  import type { CharacterClass } from "@fwo/shared";
  import CharacterImage from "$lib/character/components/CharacterImage.svelte";
  import type { Snippet } from "svelte";

  let {
    characterClass,
    name,
    lvl,
    isBot = false,
    append,
  }: {
    characterClass: CharacterClass;
    name: string;
    lvl?: number;
    isBot?: boolean;
    append?: Snippet;
  } = $props();
</script>

<div class="inline-flex justify-start gap-2">
  {#if lvl}
    {lvl}
  {/if}
  {#if !isBot}
    <CharacterImage {characterClass} small />
  {/if}
  <div class="flex-1">{name}</div>
  {#if append}
    {@render append()}
  {/if}
</div>
