// client/modules/game/components/GameStatus.tsx
import { type GameStatus as GameStatusSchema, reservedClanName } from '@fwo/shared';
import { mapValues, omit } from 'es-toolkit';
import { Description } from '@/components/Description';
import { Player } from '@/components/Player';
import { useCharacter } from '@/modules/character/store/character';
import { useGameStore } from '@/modules/game/store/useGameStore';

export function GameStatus() {
  const characterID = useCharacter((character) => character.id);
  const clan = useGameStore((state) => state.players[characterID]?.clan);
  const players = useGameStore((state) => state.players);
  const statusByClan = useGameStore((state) => state.statusByClan);
  const alliesStatus = clan
    ? statusByClan[clan?.name]
    : statusByClan[reservedClanName]?.filter(({ id }) => id === characterID);

  const enemiesStatus: Partial<Record<string, GameStatusSchema[]>> = clan
    ? omit(statusByClan, [clan.name])
    : mapValues(statusByClan, (statuses, clan) => {
        if (clan === reservedClanName) {
          return statuses?.filter(({ id }) => id !== characterID);
        }
        return statuses;
      });

  return (
    <Description header={clan?.name ?? ''}>
      {alliesStatus?.map((status) => (
        <Description.Item
          key={status.name}
          after={
            <>
              {status.hp && <>❤️{status.hp}</>}
              {status.mp && <>💧{status.mp}</>}
              {status.en && <>🔋{status.en}</>}
            </>
          }
        >
          <Player
            class={players[status.id].class}
            name={status.name}
            isBot={players[status.id].isBot}
          />
        </Description.Item>
      ))}
      {Object.entries(enemiesStatus).map(([clan, statuses]) =>
        statuses?.length ? (
          <Description key={clan} header={clan === reservedClanName ? 'Без клана' : clan}>
            {statuses?.map((status) => (
              <Description.Item key={status.id} after={<>❤️{status.hp}</>}>
                <div className="flex gap-2">
                  <Player
                    class={players[status.id].class}
                    name={status.name}
                    isBot={players[status.id].isBot}
                  />
                </div>
              </Description.Item>
            ))}
          </Description>
        ) : null,
      )}
    </Description>
  );
}

// client-sv/src/lib/game/components/GameStatus.svelte
<script lang="ts">
  import { Description } from "$lib/components/Description";
  import { getCharacterContext } from "$lib/constext/character";
  import GamePlayer from "$lib/game/components/GamePlayer.svelte";
  import { game } from "$lib/game/utils/state.svelte";
  import { reservedClanName, type GameStatus } from "@fwo/shared";
  import { mapValues, omit } from "es-toolkit";

  const character = getCharacterContext();
  const characterID = character().id;
  const clan = $derived(game.players[character().id].clan);

  const alliesStatus = $derived(
    clan
      ? game.statusByClan[clan.name]
      : game.statusByClan[reservedClanName]?.filter(
          ({ id }) => characterID === id,
        ),
  );
  const enemiesStatus: Record<string, GameStatus[]> = $derived(
    clan
      ? omit(game.statusByClan, [clan.name])
      : mapValues(game.statusByClan, (statuses, clan) => {
          if (clan === reservedClanName) {
            return statuses?.filter(({ id }) => id !== characterID);
          }
          return statuses;
        }),
  );

  const enemiesStatusEntries = $derived(Object.entries(enemiesStatus));

  $inspect(enemiesStatusEntries);
</script>

<Description.Group>
  {#snippet header()}
    {clan?.name ?? ""}
  {/snippet}

  {#each alliesStatus as status (status.name)}
    <Description.Item>
      {@const player = game.players[status.id]}
      <GamePlayer
        characterClass={player.class}
        name={player.name}
        isBot={player.isBot}
      />
      {#snippet after()}
        {#if status.hp}❤️{status.hp}{/if}
        {#if status.mp}💧{status.mp}{/if}
        {#if status.en}🔋{status.en}{/if}
      {/snippet}
    </Description.Item>
  {/each}

  {#each enemiesStatusEntries as [clan, statuses] (clan)}
    {#if statuses.length}
      <Description.Group>
        {#snippet header()}
          {clan === reservedClanName ? "Без клана" : clan}
        {/snippet}
        {#each statuses as status (status.name)}
          <Description.Item>
            {@const player = game.players[status.id]}
            <GamePlayer
              characterClass={player.class}
              name={player.name}
              isBot={player.isBot}
            />
            {#snippet after()}
              {#if status.hp}❤️{status.hp}{/if}
            {/snippet}
          </Description.Item>
        {/each}
      </Description.Group>
    {/if}
  {/each}
</Description.Group>
