// app/modules/game/components/GameStatus.tsx
import { useGameStore } from '@/modules/game/store/useGameStore';
import { Description } from '@/components/Description';
import { reservedClanName } from '@fwo/schemas';
import { useCharacter } from '@/contexts/character';

export function GameStatus() {
  const { character } = useCharacter();
  const statusByClan = useGameStore((state) => state.statusByClan);
  const status = character.clan?.id
    ? statusByClan[character.clan?.id]
    : statusByClan[reservedClanName]?.filter(({ id }) => id === character.id);

  return (
    <Description>
      {status?.map((status) => (
        <Description.Item
          key={status.name}
          after={
            <>
              {status.hp && <>❤️ {status.hp}</>}
              {status.mp && <>💧 {status.mp}</>}
              {status.en && <>🔋 {status.en}</>}
            </>
          }
        >
          {status.name}
        </Description.Item>
      ))}
      {Object.entries(statusByClan).map(([clan, statuses]) => (
        <Description key={clan} header={clan === reservedClanName ? 'Без клана' : clan}>
          {statuses?.map((status) => (
            <Description.Item key={status.id} after={<>❤️ {status.hp}</>}>
              {status.name}
            </Description.Item>
          ))}
        </Description>
      ))}
    </Description>
  );
}

// client-sv/src/lib/game/components/GameStatus.svelte
<script lang="ts">
  import { Description } from "$lib/components/Description";
  import { getCharacterContext } from "$lib/constext/character";
  import GamePlayer from "$lib/game/components/GamePlayer.svelte";
  import { game } from "$lib/game/utils/state.svelte";
  import { reservedClanName, type GameStatus } from "@fwo/shared";
  import { mapValues, omit } from "es-toolkit";

  const character = getCharacterContext();
  const clan = $derived(game.players[character().id].clan);

  const alliesStatus = $derived(
    clan
      ? game.statusByClan[clan.name]
      : game.statusByClan[reservedClanName]?.filter(
          ({ id }) => character().id === id,
        ),
  );
  const enemiesStatus: Record<string, GameStatus[]> = $derived(
    clan
      ? omit(game.statusByClan, [clan.name])
      : mapValues(game.statusByClan, (statuses, clan) => {
          if (clan === reservedClanName) {
            return statuses?.filter(({ id }) => id !== character().id);
          }
          return statuses;
        }),
  );

  const enemiesStatusEntries = $derived(Object.entries(enemiesStatus));

  $inspect(enemiesStatusEntries);
</script>

<Description.Group header={clan?.name ?? ""}>
  {#each alliesStatus as status (status.name)}
    <Description.Item>
      {@const player = game.players[status.id]}
      <GamePlayer
        characterClass={player.class}
        name={player.name}
        isBot={player.isBot}
      />
      {#snippet after()}
        {#if status.hp}❤️{status.hp}{/if}
        {#if status.mp}💧{status.mp}{/if}
        {#if status.en}🔋{status.en}{/if}
      {/snippet}
    </Description.Item>
  {/each}

  {#each enemiesStatusEntries as [clan, statuses] (clan)}
    {#if statuses.length}
      <Description.Group
        header={clan === reservedClanName ? "Без клана" : clan}
      >
        {#each statuses as status (status.name)}
          <Description.Item>
            {@const player = game.players[status.id]}
            <GamePlayer
              characterClass={player.class}
              name={player.name}
              isBot={player.isBot}
            />
            {#snippet after()}
              {#if status.hp}❤️{status.hp}{/if}
            {/snippet}
          </Description.Item>
        {/each}
      </Description.Group>
    {/if}
  {/each}
</Description.Group>
