// client/modules/items/components/ItemComponents.tsx
import type { Item, ItemComponent } from '@fwo/shared';
import type { FC } from 'react';

import { useItemComponents } from '@/modules/items/hooks/useItemComponents';
import { useCharacter } from '@/contexts/character';
import classNames from 'classnames';

export const ItemComponents: FC<{ item: Item }> = ({ item }) => {
  const { getComponents, getComponentImage } = useItemComponents();
  const { character } = useCharacter();

  const hasComponents = (component: ItemComponent) => {
    return (character.components[component] ?? 0) >= (item.craft?.components[component] ?? 0);
  };

  return (
    <div className="flex gap-4 flex-wrap">
      {getComponents(item).map((component) => (
        <div key={component} className="flex items-center gap-1">
          <img height={20} width={20} src={getComponentImage(component)} />
          <span className={classNames({ 'text-red-500': !hasComponents(component) })}>
            {item.craft?.components[component]}/{character.components[component] ?? 0}
          </span>
        </div>
      ))}
    </div>
  );
};

// client/src/lib/item/components/ItemComponents.svelte
<script lang="ts">
  import type { Item, ItemComponent } from "@fwo/shared";
  import {
    componentsImageMap,
    getItemComponents,
  } from "$lib/constants/components";
  import { getCharacterContext } from "$lib/constext/character";

  type Props = {
    item: Item;
  };

  const { item }: Props = $props();
  const character = getCharacterContext();
  const characterComponents = $derived(character().components);

  const hasComponents = (component: ItemComponent) => {
    return (
      (characterComponents[component] ?? 0) >=
      (item.craft?.components[component] ?? 0)
    );
  };

  const components = $derived(getItemComponents(item));
</script>

{#if components.length}
  <div class="flex gap-4 flex-wrap text-sm items-center">
    <span class="opacity-75">Компоненты:</span>
    {#each components as component (component)}
      <div class="flex items-center gap-1">
        <img
          height={18}
          width={18}
          src={componentsImageMap[component]}
          alt={component.toString()}
          class="inline-block"
        />
        <span
          class={{ "text-red-500 font-semibold": !hasComponents(component) }}
        >
          {item.craft?.components[component]}
          /
          {characterComponents[component] ?? 0}
        </span>
      </div>
    {/each}
  </div>
{/if}
