// client/modules/items/components/ItemPassive.tsx
import { type Item, QuestType } from '@fwo/shared';
import type { FC } from 'react';

const QUEST_DESCRIPTION = {
  [QuestType.Damage]: 'Нанести урон',
  [QuestType.Kills]: 'Убить противников',
  [QuestType.Heal]: 'Восстановить здоровья',
};

export const ItemPassive: FC<{ passive: Required<Item>['passive'] }> = ({ passive }) => {
  return (
    <div>
      <div className="flex justify-between items-baseline">
        <span>{passive.name}</span>
        <span className="text-xs">{passive.level} lvl</span>
      </div>

      {passive.quest && (
        <span className="text-sm">
          {QUEST_DESCRIPTION[passive.quest.type]}: {passive.quest.progress}/{passive.quest.goal}
        </span>
      )}
    </div>
  );
};

// client/src/lib/item/components/ItemPassive.svelte
<script lang="ts">
  import { type Item, QuestType } from "@fwo/shared";

  const QUEST_DESCRIPTION: Record<QuestType, string> = {
    [QuestType.Damage]: "Нанести урон",
    [QuestType.Kills]: "Убить противников",
    [QuestType.Heal]: "Восстановить здоровья",
  };

  type Props = {
    passive: NonNullable<Item["passive"]>;
  };

  const { passive }: Props = $props();
</script>

<div class="flex flex-col gap-1 text-sm">
  <div class="flex justify-between items-baseline">
    <span>{passive.name}</span>
    <span class="text-xs opacity-75">{passive.level} lvl</span>
  </div>

  {#if passive.quest}
    <span class="text-xs opacity-75">
      {QUEST_DESCRIPTION[passive.quest.type]}:
      {passive.quest.progress}/{passive.quest.goal}
    </span>
  {/if}
</div>
