// client/context/popup.tsx
// import { type PopupHandle, PopupOverlay } from '@/components/Popup';
import {
  createContext,
  type FC,
  type PropsWithChildren,
  type ReactNode,
  useCallback,
  useDeferredValue,
  useRef,
  useState,
} from 'react';
import { Button } from '@/components/Button';

type PopupOptions = {
  title?: string;
  message: ReactNode;
  onConfirm?: (done: () => void) => void;
  onCancel?: () => void;
  type?: 'confirm' | 'info';
};

type PopupContextType = {
  info: (options: Omit<PopupOptions, 'type'>) => void;
  confirm: (options: Omit<PopupOptions, 'type'>) => void;
  show: (options: PopupOptions) => void;
  close: () => void;
  visible: boolean;
};

export const PopupContext = createContext<PopupContextType | undefined>(undefined);

export const PopupProvider: FC<PropsWithChildren> = ({ children }) => {
  const popupRef = useRef<PopupHandle>(null);
  const [popupState, setPopupState] = useState<{
    type: 'confirm' | 'info';
    options: PopupOptions;
  } | null>(null);
  const visible = useDeferredValue(!!popupState?.type, false);

  const show = (options: PopupOptions) => {
    setPopupState({ type: options.type ?? 'info', options });
    popupRef.current?.open();
  };

  const info = (options: Omit<PopupOptions, 'type'>) => show({ ...options, type: 'info' });
  const confirm = (options: Omit<PopupOptions, 'type'>) => show({ ...options, type: 'confirm' });

  const closePopup = useCallback(() => {
    popupRef.current?.close();
    setPopupState(null);
  }, []);

  const handleConfirm = async () => {
    if (popupState?.options.onConfirm) {
      closePopup();
      await popupState?.options.onConfirm(closePopup);
    } else {
      closePopup();
    }
  };

  return (
    <PopupContext.Provider value={{ show, close, info, confirm, visible }}>
      {children}

      <PopupOverlay ref={popupRef} onClose={closePopup}>
        <div className="flex flex-col p-4 gap-4">
          {popupState?.options.title ? (
            <span className="font-semibold">{popupState.options.title}</span>
          ) : null}
          {popupState?.options.message}
          {popupState?.type === 'confirm' ? (
            <div className="flex gap-2">
              <Button className="flex-1" onClick={closePopup}>
                Отмена
              </Button>
              <Button className="flex-1 is-primary" onClick={handleConfirm}>
                Ок
              </Button>
            </div>
          ) : null}
          {popupState?.type === 'info' ? (
            <div className="flex gap-2">
              <Button className="flex-1 is-primary" onClick={handleConfirm}>
                Ок
              </Button>
            </div>
          ) : null}
        </div>
      </PopupOverlay>
    </PopupContext.Provider>
  );
};

// client-sv/src/lib/components/Popup.svelte
<script lang="ts">
  import Button from "$lib/components/Button.svelte";
  import type { PopupOptions } from "$lib/constext/popup";
  import { themeParams, useSignal } from "@tma.js/sdk-svelte";
  import type { MouseEventHandler, SvelteHTMLElements } from "svelte/elements";

  const { children, ...restProps }: SvelteHTMLElements["dialog"] = $props();

  let dialog: HTMLDialogElement;
  let state = $state<PopupOptions | null>(null);
  const isDark = useSignal(themeParams.isDark);

  export const show = (options: PopupOptions) => {
    state = options;
    dialog?.showModal();
  };

  export const close = () => {
    dialog?.close();
    state = null;
  };

  export const info = (options: Omit<PopupOptions, "type">) =>
    show({ type: "info", ...options });

  export const confirm = (options: Omit<PopupOptions, "type">) =>
    show({ type: "confirm", ...options });

  const handleClick: MouseEventHandler<HTMLDialogElement> = (e) => {
    e.preventDefault();

    if (e.target === dialog) {
      dialog.close();
    } else {
      restProps.onclick?.(e);
    }
  };

  const handleConfirm = async () => {
    if (state?.onConfirm) {
      close();
      await state.onConfirm(close);
    } else {
      close();
    }
  };

  const handleCancel = () => {
    if (state?.onCancel) {
      close();
      state.onCancel();
    } else {
      close();
    }
  };
</script>

<dialog
  bind:this={dialog}
  class={[
    "nes-dialog is-rounded",
    {
      "is-dark": $isDark,
    },
  ]}
  onclick={handleClick}
  {...restProps}
>
  <div class="flex flex-col p-4 gap-4">
    {#if state?.title}
      <span class="font-semibold">{state.title}</span>
    {/if}

    {state?.message}
    {#if state?.type === "confirm"}
      <div class="flex gap-2">
        <Button class="flex-1" onclick={handleCancel}>Отмена</Button>
        <Button class="flex-1 is-primary" onclick={handleConfirm}>Ок</Button>
      </div>
    {:else if state?.type === "info"}
      <div class="flex gap-2">
        <Button class="flex-1 is-primary" onclick={handleConfirm}>Ок</Button>
      </div>
    {/if}
  </div>
</dialog>

<style>
  .nes-dialog {
    margin: auto;
    padding: 0;
    background-color: var(--tg-theme-secondary-bg-color);
    border-image-repeat: stretch !important;
    max-width: 85% !important;
    white-space: pre-wrap;
    min-width: 50vw;
  }
</style>
