// client-sv/src/lib/clan/components/ClanList.svelte
<script lang="ts">
  import ClanListItem from "./ClanListItem.svelte";
  import type { Clan } from "@fwo/shared";

  let {
    clans,
    isLoading,
    isRequested,
    onCreateRequest,
    onCancelRequest,
  }: {
    clans: Clan[];
    isLoading: boolean;
    isRequested: (clan: Clan) => boolean;
    onCreateRequest: (id: string) => void;
    onCancelRequest: (id: string) => void;
  } = $props();
</script>

<div class="flex flex-col gap-2">
  {#each clans as clan (clan.id)}
    <ClanListItem
      {clan}
      {isLoading}
      requested={isRequested(clan)}
      {onCreateRequest}
      {onCancelRequest}
    />
  {/each}
</div>

// client/modules/clan/components/ClanList.tsx
import { ClanListItem } from '@/modules/clan/components/ClanListItem';
import type { Clan } from '@fwo/shared';
import type { FC } from 'react';

export const ClanList: FC<{
  clans: Clan[];
  isLoading: boolean;
  isRequested: (clan: Clan) => boolean;
  onCreateRequest: (id: string) => void;
  onCancelRequest: (id: string) => void;
}> = ({ clans, isLoading, isRequested, onCreateRequest, onCancelRequest }) => {
  return (
    <div className="flex flex-col gap-2">
      {clans.map((clan) => (
        <ClanListItem
          key={clan.id}
          clan={clan}
          isLoading={isLoading}
          requested={isRequested(clan)}
          onCreateRequest={onCreateRequest}
          onCancelRequest={onCancelRequest}
        />
      ))}
    </div>
  );
};
