// client/modules/clan/components/ClanPlayers.tsx
import type { CharacterPublic } from '@fwo/shared';
import type { FC, ReactNode } from 'react';
import { Description } from '@/components/Description';
import { CharacterImage } from '@/modules/character/components/CharacterImage';

export const ClanPlayers: FC<{
  characters: CharacterPublic[];
  after?: (character: CharacterPublic) => ReactNode;
}> = ({ characters, after }) => {
  return (
    <Description>
      {characters.map((character) => (
        <Description.Item key={character.id} after={after?.(character)}>
          <div className="flex gap-2">
            <CharacterImage characterClass={character.class} small /> {character.name} (
            {character.lvl})
          </div>
        </Description.Item>
      ))}
    </Description>
  );
};

// client-sv/src/lib/clan/components/ClanPlayers.svelte
<script lang="ts">
  import type { CharacterPublic } from "@fwo/shared";
  import CharacterImage from "$lib/character/components/CharacterImage.svelte";
  import DescriptionGroup from "$lib/components/Description/description-group.svelte";
  import DescriptionItem from "$lib/components/Description/description-item.svelte";

  const { characters }: { characters: CharacterPublic[] } = $props();
</script>

<DescriptionGroup>
  {#each characters as character (character.id)}
    <DescriptionItem>
      <div class="flex gap-2 items-center">
        <CharacterImage characterClass={character.class} small />
        {character.name} ({character.lvl})
      </div>
    </DescriptionItem>
  {/each}
</DescriptionGroup>
