// client/src/lib/game/components/GameOrderReady.svelte
<script lang="ts">
  import Button from "$lib/components/Button.svelte";
  import { toggleReady } from "$lib/game/utils/ready.svelte";
  import { game } from "$lib/game/utils/state.svelte";
</script>

<Button
  {@attach toggleReady.attach()}
  class={[
    "mb-2",
    {
      "is-success": !game.ready,
      "is-error": game.ready,
      invisible: !game.canOrder,
    },
  ]}
>
  {#if game.ready}
    Продолжить ход
  {:else}
    Завершить ход
  {/if}
</Button>

// client/modules/game/components/GameOrderReady.tsx
import { Button } from '@/components/Button';
import { useGameOrderReady } from '@/modules/game/hooks/useGameOrderReady';
import { useGameStore } from '@/modules/game/store/useGameStore';
import classNames from 'classnames';

export const GameOrderReady = () => {
  const { isReady, handleReady, isPending } = useGameOrderReady();
  const canOrder = useGameStore((state) => state.canOrder);

  return !isReady ? (
    <Button
      onClick={handleReady}
      className={classNames('is-success mb-2', { invisible: !canOrder })}
      disabled={isPending}
    >
      Завершить ход
    </Button>
  ) : (
    <Button
      onClick={handleReady}
      className={classNames('is-error mb-2', { invisible: !canOrder })}
      disabled={isPending}
    >
      Продолжить ход
    </Button>
  );
};
