// client/modules/character/components/CharacterImage.tsx
import type { CharacterClass } from '@fwo/shared';
import { createEffect, createMemo } from 'solid-js';
import { drawCharacter } from '@/modules/character/hooks/useDrawCharacter';

export function CharacterImage(props: { characterClass: CharacterClass; small?: boolean }) {
  let canvas!: HTMLCanvasElement;

  const width = createMemo(() => (props.small ? 20 : 100));
  const height = createMemo(() => (props.small ? 20 : 100));

  createEffect(
    () => props.characterClass,
    (characterClass) => {
      drawCharacter(canvas, characterClass);
    },
  );

  return <canvas ref={canvas} style={{ margin: 'auto' }} width={width()} height={height()} />;
}

// app/components/Character/CharacterImage.tsx
import { useEffect, useRef } from 'react';
import { useCharacter } from '@/hooks/useCharacter';
import { drawCharacter } from './drawCharacter';

export const CharacterImage = () => {
  const { character } = useCharacter();
  const canvas = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if (canvas.current) {
      drawCharacter(canvas.current, character);
    }
  }, [character]);

  return (
    <canvas ref={canvas} style={{ display: 'block', margin: 'auto' }} width={200} height={200} />
  );
};
