// client/modules/forge/components/ForgeList.tsx
import { getItemPrice, type Item } from '@fwo/shared';
import type { FC } from 'react';
import { forgeItem } from '@/api/inventory';
import { ItemModal } from '@/modules/items/components/ItemModal';
import { useRequest } from '@/hooks/useRequest';
import { Button } from '@/components/Button';
import { Placeholder } from '@/components/Placeholder';
import { every } from 'es-toolkit/compat';
import { forgeClanItem } from '@/api/clan';
import { useCharacter } from '@/modules/character/store/character';
import { useSyncCharacter } from '@/modules/character/hooks/useSyncCharacter';
import { usePopup } from '@/hooks/usePopup';

export const ForgeList: FC<{ items: Item[]; clanForge?: boolean }> = ({ items, clanForge }) => {
  const gold = useCharacter((character) => character.gold);
  const components = useCharacter((character) => character.components);
  const { syncCharacter } = useSyncCharacter();
  const [_, makeRequest] = useRequest();
  const popup = usePopup();

  const canForge = (item: Item) => {
    if (gold < item.price * 0.2) {
      return false;
    }

    return every(item.craft?.components, (value, key) => (components[key] ?? 0) >= (value ?? 0));
  };

  const handleForge = async (item: Item) => {
    await makeRequest(async () => {
      if (clanForge) {
        await forgeClanItem(item.code);
      } else {
        await forgeItem(item.code);
      }
      popup.info({ message: `Ты создал ${item.info.name}` });
    });
    await syncCharacter();
  };

  return items.length ? (
    <div className="flex flex-col gap-2">
      {items.map((item) => (
        <ItemModal
          key={item.code}
          item={item}
          trigger={<Button className="text-start">{item.info.name}</Button>}
          footer={
            <div className="flex items-center justify-between gap-4">
              <Button
                className="flex-1"
                disabled={!canForge(item)}
                onClick={() => handleForge(item)}
              >
                Создать за {getItemPrice(item.price, item.tier)}💰
              </Button>
              <div>У тебя {gold}💰</div>
            </div>
          }
          showComponents
        />
      ))}
    </div>
  ) : (
    <Placeholder description="Ничего не найдено" />
  );
};

// client/src/lib/forge/components/ForgeList.svelte
<script lang="ts">
  import { getItemPrice, type Item } from "@fwo/shared";
  import { invalidate } from "$app/navigation";
  import { client, createRequest } from "$lib/api";
  import Button from "$lib/components/Button.svelte";
  import Card from "$lib/components/Card.svelte";
  import { popup } from "$lib/components/Popup/popup.svelte";
  import { getCharacterContext } from "$lib/constext/character";
  import ItemInfo from "$lib/item/components/ItemInfo.svelte";
  import { createRequestRunner } from "$lib/utils/create-request.svelte";

  type Props = {
    items: Item[];
    title?: string;
    clanForge?: boolean;
  };

  let { items, title = "Кузница", clanForge = false }: Props = $props();

  const character = getCharacterContext();
  let selectedItem = $derived(items[0]);

  const canForge = (item: Item) => {
    const c = character();
    if (c.gold < item.price * 0.2) return false;
    if (!item.craft?.components) return true;
    return Object.entries(item.craft.components).every(
      ([key, value]) =>
        (c.components[key as keyof typeof c.components] ?? 0) >= (value ?? 0),
    );
  };

  const forgeItem = createRequestRunner(async (item: Item) => {
    if (clanForge) {
      await createRequest(client.clan.forge.item[":code"].$post)({
        param: { code: item.code },
      });
    } else {
      await createRequest(client.inventory.forge[":code"].$post)({
        param: { code: item.code },
      });
    }

    popup.info({ message: `Ты создал ${item.info.name}` });
    await invalidate("app:character");
  });
</script>

<div class="h-full flex flex-col">
  <Card header={title} class="mb-1">
    <div class="h-[42vh] overflow-y-auto">
      {#if items.length}
        <div class="flex flex-col gap-1.5">
          {#each items as item (item.code)}
            <Button
              class={[
                "flex-1 text-start",
                { "is-primary": selectedItem?.code === item.code },
              ]}
              onclick={() => (selectedItem = item)}
            >
              <div class="flex justify-between items-center text-sm">
                <span>{item.info.name}</span>
                <span class="opacity-75">
                  {getItemPrice(item.price, item.tier)}💰
                </span>
              </div>
            </Button>
          {/each}
        </div>
      {:else}
        <div class="text-sm opacity-50">Ничего не найдено</div>
      {/if}
    </div>
  </Card>

  <Card header={selectedItem?.info.name} class="flex-1 flex flex-col mt-0">
    {#if selectedItem}
      <ItemInfo item={selectedItem} showComponents={true}>
        {#snippet footer(item)}
          <div class="flex items-center justify-between gap-3 mt-1">
            <Button
              {@attach forgeItem.attach(
                { disabled: () => !canForge(item) },
                item,
              )}
              class="flex-1 is-primary py-1.5!"
            >
              Создать за {getItemPrice(item.price, item.tier)}💰
            </Button>
            <div class="whitespace-nowrap text-xs">
              У тебя {character().gold}💰
            </div>
          </div>
        {/snippet}
      </ItemInfo>
    {:else}
      <div class="text-sm opacity-50">Выбери предмет</div>
    {/if}
  </Card>
</div>
