// client/src/lib/lobby/components/LobbyList.svelte
<script lang="ts">
  import { type CharacterPublic, reservedClanName } from "@fwo/shared";
  import { groupBy } from "es-toolkit";
  import DescriptionGroup from "$lib/components/Description/description-group.svelte";
  import DescriptionItem from "$lib/components/Description/description-item.svelte";
  import Player from "./Player.svelte";

  type Props = {
    searchers: CharacterPublic[];
  };

  let { searchers }: Props = $props();

  const searchersByClan = $derived(
    groupBy(searchers, ({ clan }) => clan?.name ?? reservedClanName),
  );
</script>

{#if searchers.length}
  {#each Object.entries(searchersByClan) as [clan, clanSearchers] (clan)}
    <DescriptionGroup header={clan === reservedClanName ? "Без клана" : clan}>
      {#each clanSearchers as searcher (searcher.id)}
        <DescriptionItem>
          <Player
            characterClass={searcher.class}
            name={searcher.name}
            lvl={searcher.lvl}
          />
        </DescriptionItem>
      {/each}
    </DescriptionGroup>
  {/each}
{:else}
  <p class="opacity-50">Никого нет</p>
{/if}

// client/modules/lobby/components/LobbyList.tsx
import { type CharacterPublic, reservedClanName } from '@fwo/shared';
import { groupBy } from 'es-toolkit';
import type { FC } from 'react';
import { Description } from '@/components/Description';
import { Placeholder } from '@/components/Placeholder';
import { Player } from '@/components/Player';

export const LobbyList: FC<{ searchers: CharacterPublic[] }> = ({ searchers }) => {
  const searchersByClan = groupBy(searchers, ({ clan }) => clan?.name ?? reservedClanName);

  return (
    <>
      {searchers.length ? (
        Object.entries(searchersByClan).map(([clan, searchers]) => (
          <Description key={clan} header={clan === reservedClanName ? 'Без клана' : clan}>
            {searchers?.map((searcher) => (
              <Description.Item key={searcher.id}>
                <Player class={searcher.class} name={searcher.name} lvl={searcher.lvl} />
              </Description.Item>
            ))}
          </Description>
        ))
      ) : (
        <Placeholder description="Никого нет" />
      )}
    </>
  );
};
