// client/modules/forge/components/ForgeList.tsx
import { getItemPrice, type Item } from '@fwo/shared';
import type { FC } from 'react';
import { forgeItem } from '@/api/inventory';
import { ItemModal } from '@/modules/items/components/ItemModal';
import { useRequest } from '@/hooks/useRequest';
import { Button } from '@/components/Button';
import { Placeholder } from '@/components/Placeholder';
import { every } from 'es-toolkit/compat';
import { forgeClanItem } from '@/api/clan';
import { useCharacter } from '@/modules/character/store/character';
import { useSyncCharacter } from '@/modules/character/hooks/useSyncCharacter';
import { usePopup } from '@/hooks/usePopup';

export const ForgeList: FC<{ items: Item[]; clanForge?: boolean }> = ({ items, clanForge }) => {
  const gold = useCharacter((character) => character.gold);
  const components = useCharacter((character) => character.components);
  const { syncCharacter } = useSyncCharacter();
  const [_, makeRequest] = useRequest();
  const popup = usePopup();

  const canForge = (item: Item) => {
    if (gold < item.price * 0.2) {
      return false;
    }

    return every(item.craft?.components, (value, key) => (components[key] ?? 0) >= (value ?? 0));
  };

  const handleForge = async (item: Item) => {
    await makeRequest(async () => {
      if (clanForge) {
        await forgeClanItem(item.code);
      } else {
        await forgeItem(item.code);
      }
      popup.info({ message: `Ты создал ${item.info.name}` });
    });
    await syncCharacter();
  };

  return items.length ? (
    <div className="flex flex-col gap-2">
      {items.map((item) => (
        <ItemModal
          key={item.code}
          item={item}
          trigger={<Button className="text-start">{item.info.name}</Button>}
          footer={
            <div className="flex items-center justify-between gap-4">
              <Button
                className="flex-1"
                disabled={!canForge(item)}
                onClick={() => handleForge(item)}
              >
                Создать за {getItemPrice(item.price, item.tier)}💰
              </Button>
              <div>У тебя {gold}💰</div>
            </div>
          }
          showComponents
        />
      ))}
    </div>
  ) : (
    <Placeholder description="Ничего не найдено" />
  );
};

// client-sv/src/lib/forge/components/ForgeList.svelte
<script lang="ts">
  import Button from "$lib/components/Button.svelte";
  import Modal from "$lib/components/Modal.svelte";
  import { getCharacterContext } from "$lib/constext/character";
  import { makeRequest } from "$lib/utils/make-request.svelte";
  import { client, createRequest } from "$lib/api";
  import { getItemPrice, type Item } from "@fwo/shared";
  import { invalidate } from "$app/navigation";
  import { popup } from "$lib/components/Popup/popup.svelte";

  let { items, clanForge = false }: { items: Item[]; clanForge?: boolean } =
    $props();

  const character = getCharacterContext();

  const canForge = (item: Item) => {
    const c = character();
    if (c.gold < item.price * 0.2) return false;
    if (!item.craft?.components) return true;
    return Object.entries(item.craft.components).every(
      ([key, value]) =>
        (c.components[key as keyof typeof c.components] ?? 0) >= (value ?? 0),
    );
  };

  const handleForge = async (item: Item) => {
    await makeRequest(async () => {
      if (clanForge) {
        await createRequest(client.clan.forge.item[":code"].$post)({
          param: { code: item.code },
        });
      } else {
        await createRequest(client.inventory.forge[":code"].$post)({
          param: { code: item.code },
        });
      }

      popup.info({ message: `Ты создал ${item.info.name}` });
    });
    await invalidate("app:character");
  };
</script>

{#if items.length}
  <div class="flex flex-col gap-2">
    {#each items as item (item.code)}
      <Modal header={item.info.name}>
        {#snippet trigger()}
          <Button class="text-start">{item.info.name}</Button>
        {/snippet}
        <div class="flex flex-col gap-2">
          <p>{item.info.description}</p>
          <div class="flex items-center justify-between gap-4">
            <Button
              class="flex-1"
              disabled={!canForge(item)}
              onclick={() => handleForge(item)}
            >
              Создать за {getItemPrice(item.price, item.tier)}💰
            </Button>
            <div>У тебя {character().gold}💰</div>
          </div>
        </div>
      </Modal>
    {/each}
  </div>
{:else}
  <p>Ничего не найдено</p>
{/if}
